### ISSUE TITLE
Config rejected when there is a headless service2 point to a same set of pods of service1 with different appProtocol

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#11513]
### What happened?

Steps to reproduce:

1. Create a mesh cluster and some HTTP services, we can use the counter demo.
2. Creating one headless services point to pods that are selected by an existing service, verify the functionalities still work as expected
    Fail:
        1. When the headless service has an empty `appProtocol` with other services that select the pod and has a `appProtocol` as `http`, it causes NACK loops and HTTP 503 errors when requesting the service using the URL of other services. (installed headless-1 with appProtocol: tcp, and selects pods app: counter-demo, requests with `demo-app.kuma-demo.svc.cluster.local:5000` fails with 503)  (logs1)
        2. After correcting the `appProtocol` on the headless service to `http`, the traffic came back.

logs1:

```
2024-09-20T09:30:50.453Z        INFO    xds.nack-backoff        config was previously rejected by Envoy. Applying backoff before resending it   {"backoff": "5s", "nodeID": "default.demo-app-d8d8bdb97-z45zd.kuma-demo", "reason": "Error adding/updating cluster(s) localhost:5000: Proto constraint validation failed (field: \"upstream_protocol_options\", reason: is required): common_http_protocol_options {\n  idle_timeout {\n    seconds: 7200\n  }\n  max_connection_duration {\n  }\n  max_stream_duration {\n  }\n}\n"}
2024-09-20T09:30:55.456Z        INFO    xds.status-tracker      config rejected {"proxyName": "demo-app-d8d8bdb97-z45zd.kuma-demo", "mesh": "default", "streamID": 2, "type": "Cluster", "resourceVersion": "67fb715e-297a-487b-ad96-c3c8737208be"}
2024-09-20T09:30:55.456Z        INFO    xds.nack-backoff        config was previously rejected by Envoy. Applying backoff before resending it   {"backoff": "5s", "nodeID": "default.demo-app-d8d8bdb97-z45zd.kuma-demo", "reason": "Error adding/updating cluster(s) localhost:5000: Proto constraint validation failed (field: \"upstream_protocol_options\", reason: is required): common_http_protocol_options {\n  idle_timeout {\n    seconds: 7200\n  }\n  max_connection_duration {\n  }\n  max_stream_duration {\n  }\n}\n"}
2024-09-20T09:31:00.459Z        INFO    xds.status-tracker      config rejected {"proxyName": "demo-app-d8d8bdb97-z45zd.kuma-demo", "mesh": "default", "streamID": 2, "type": "Cluster", "resourceVersion": "67fb715e-297a-487b-ad96-c3c8737208be"}
2024-09-20T09:31:00.459Z        INFO    xds.nack-backoff        config was previously rejected by Envoy. Applying backoff before resending it   {"backoff": "5s", "nodeID": "default.demo-app-d8d8bdb97-z45zd.kuma-demo", "reason": "Error adding/updating cluster(s) localhost:5000: Proto constraint validation failed (field: \"upstream_protocol_options\", reason: is required): common_http_protocol_options {\n  idle_timeout {\n    seconds: 7200\n  }\n  max_connection_duration {\n  }\n  max_stream_duration {\n  }\n}\n"}
```

It's found in a recent TestFriday session. 
More details on this page: https://github.com/Kong/team-mesh/issues/300

**Comment by lahabana** [comment]
Is this a `MeshService` issue or a legacy service issue?

**Comment by lahabana** [comment]
If it's only for legacy service let's close this as this is no longer a problem with MeshService

**Comment by jijiechen** [comment]
This was first found on a Test Friday activity and we did not verify with `MeshService`

**Comment by lukidzi** [comment]
It seems there is an issue with `meshService.mode: Exclusive` after adding first headless service with a different protocol:
dp logs
```
│ kuma-sidecar [2025-02-25 19:31:16.854][27][warning][config] [source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138] gRPC config for type.googleapis.com/envoy.config.cluster.v3.Cluster rejected: Error adding/updating cluster(s) localhost:5000: Proto constraint validatio │
│ n failed (field: "upstream_protocol_options", reason: is required): common_http_protocol_options {                                                                                                                                                                                               │
│ kuma-sidecar   idle_timeout {                                                                                                                                                                                                                                                                    │
│ kuma-sidecar     seconds: 7200                                                                                                                                                                                                                                                                   │
│ kuma-sidecar   }                                                                                                                                                                                                                                                                                 │
│ kuma-sidecar   max_connection_duration {                                                                                                                                                                                                                                                         │
│ kuma-sidecar   }                                                                                                                                                                                                                                                                                 │
│ kuma-sidecar   max_stream_duration {                                                                                                                                                                                                                                                             │
│ kuma-sidecar   }                                                                                                                                                                                                                                                                                 │
│ kuma-sidecar }                                                                                                                                                                                                                                                                                   │
│ kuma-sidecar                                                                                                                                                                                                                                                                                     │
│
```
CP logs
```
2025-02-25T19:32:11.909Z	INFO	xds.status-tracker	config rejected	{"proxyName": "demo-app-b4f98898-9rfh4.kuma-demo", "mesh": "default", "streamID": 1, "type": "Cluster", "resourceVersion": "21c73e83-8fe2-49b6-b774-31ddeada97fa"}
2025-02-25T19:32:11.909Z	INFO	xds.nack-backoff	config was previously rejected by Envoy. Applying backoff before resending it	{"backoff": "5s", "nodeID": "default.demo-app-b4f98898-9rfh4.kuma-demo", "reason": "Error adding/updating cluster(s) localhost:5000: Proto constraint validation failed (field: \"upstream_protocol_options\", reason: is required): common_http_protocol_options {\n  idle_timeout {\n    seconds: 7200\n  }\n  max_connection_duration {\n  }\n  max_stream_duration {\n  }\n}\n"}
```


headless service (protocol TCP, while original demo-app service has HTTP)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: headless-1
  namespace: kuma-demo
spec:
  clusterIP: None
  selector:
    app: demo-app
  ports:
  - name: http-port
    protocol: TCP
    port: 5000
    targetPort: 5000
```

**Comment by lukidzi** [comment]
xref: https://github.com/kumahq/kuma/issues/2799

**Comment by lukidzi** [comment]
Should be fixed by https://github.com/kumahq/kuma/pull/12760

**Comment by lahabana** [comment]
@jijiechen can you very and close if it's confirmed as fixed?

**Comment by jijiechen** [comment]
No, the error persists on the latest version. 

It's reproducable by four simple steps:

1. install the mesh on k8s
2. install the demo app: `kubectl apply -f https://raw.githubusercontent.com/kumahq/kuma-counter-demo/refs/heads/master/demo.yaml`
3. install the following service onto the cluster
4. run `kubectl run -n kuma-demo mycurlpod --image=nicolaka/netshoot -i --tty -- bash` and try to access demo app using `curl -v demo-app.kuma-demo.svc.cluster.local:5000`

```
apiVersion: v1
kind: Service
metadata:
  name: headless-2
  namespace: kuma-demo
spec:
  clusterIP: None
  selector:
    app: demo-app
  ports:
  - name: http-port
    protocol: TCP
    port: 5000
    targetPort: 5000
```


Failure: 

```
* Host demo-app.kuma-demo.svc.cluster.local:5000 was resolved.
* IPv6: (none)
* IPv4: 10.43.158.55
*   Trying 10.43.158.55:5000...
* Connected to demo-app.kuma-demo.svc.cluster.local (10.43.158.55) port 5000
> GET / HTTP/1.1
> Host: demo-app.kuma-demo.svc.cluster.local:5000
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 502 Bad Gateway
< content-length: 110
< content-type: text/plain
< date: Tue, 13 May 2025 09:47:26 GMT
< server: envoy
<
* Connection #0 to host demo-app.kuma-demo.svc.cluster.local left intact
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: protocol error
```

**Comment by lahabana** [comment]
@jijiechen can we also check with MeshService. If it's only on legacy service let's not fix this and mark this as a shortcoming of the old system

**Comment by jijiechen** [comment]
The issue has been solved on master
I verified using latest code 67a44fc1df9aa
