### ISSUE TITLE
`ads_cluster` + `STRICT_DNS` tries to resolve IPV6 addr

### ISSUE THREAD

**Issue by jgrund** [kumahq/kuma#2000]
### Summary

If the `ads_cluster` selects `STRICT_DNS`, it will try to resolve an IPV6 address every 5 seconds. This is because 
`dns_lookup_family` defaults to `AUTO` when unset and `AUTO` [tries IPV6 first](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#enum-config-cluster-v3-cluster-dnslookupfamily). 

If this occurs and the upstream server cannot resolve a lookup for an IPV6 address, there will be a `NXDomain` returned every 5 seconds due to `dns_failure_refresh_rate` \ `dns_refresh_rate`.

We should additionally set whether to use IPV4 / IPV6 for `dns_lookup_family`, much like is done for `StrictDNSClusterConfigurer`:

https://github.com/kumahq/kuma/blob/bd14216f56ffb63b3c071a89f45746d2da38d103/pkg/xds/envoy/clusters/v2/strict_dns_cluster_configurer.go#L19-L31

### Additional Details & Logs

- Version: Kuma 1.1.6
- Configuration: Universal
- Platform and Operating System: CentOS 7

**Comment by lahabana** [comment]
This happens in the `template_v3.go` when bootstrapping.

**Comment by jakubdyszkiewicz** [comment]
I'd say this is by design. When we specify cp-address in kuma-dp this may be hostname that may or may not resolve to IPV6.

We can force IPV4 when IP of the `Dataplane#networking` is IPV4 just like we do for in-cluster communication between services. Would this be a viable option @nickolaev ?

**Comment by jgrund** [comment]
Is this fixed by https://github.com//kumahq/kuma/pull/3089 ?

**Comment by lahabana** [comment]
#3089 doesn't fix the issue as the ads_cluster is set on bootstrap and the mentioned PR is about the embedded DNS.

Threfore issue is still valid there's `Cluster_V4_PREFERRED` option but then the opposite issue will exist.
I guess there's still the option of having an IPv6_disabled flag on the dataplane which would enable us to specify the correct `dns_lookup_family`.

**Comment by jgrund** [comment]
FWIW, my current version of patching this for my IPV4 only cluster looks like:

```diff
diff --git a/pkg/xds/bootstrap/template_v3.go b/pkg/xds/bootstrap/template_v3.go
index a138b7306..4c8987951 100644
--- a/pkg/xds/bootstrap/template_v3.go
+++ b/pkg/xds/bootstrap/template_v3.go
@@ -131,6 +131,7 @@ func genConfig(parameters configParameters) (*envoy_bootstrap_v3.Bootstrap, erro
 					ConnectTimeout:       util_proto.Duration(parameters.XdsConnectTimeout),
 					Http2ProtocolOptions: &envoy_core_v3.Http2ProtocolOptions{},
 					LbPolicy:             envoy_cluster_v3.Cluster_ROUND_ROBIN,
+					DnsLookupFamily:      envoy_cluster_v3.Cluster_V4_ONLY,
 					UpstreamConnectionOptions: &envoy_cluster_v3.UpstreamConnectionOptions{
 						TcpKeepalive: &envoy_core_v3.TcpKeepalive{
 							KeepaliveProbes:   util_proto.UInt32(3),
@@ -163,6 +164,7 @@ func genConfig(parameters configParameters) (*envoy_bootstrap_v3.Bootstrap, erro
 					ConnectTimeout:       util_proto.Duration(parameters.XdsConnectTimeout),
 					Http2ProtocolOptions: &envoy_core_v3.Http2ProtocolOptions{},
 					LbPolicy:             envoy_cluster_v3.Cluster_ROUND_ROBIN,
+					DnsLookupFamily:      envoy_cluster_v3.Cluster_V4_ONLY,
 					UpstreamConnectionOptions: &envoy_cluster_v3.UpstreamConnectionOptions{
 						TcpKeepalive: &envoy_core_v3.TcpKeepalive{
 							KeepaliveProbes:   util_proto.UInt32(3),

```

Without this change, I see the following repeated over and over and my service mesh takes over a minute to start up:

```
18:47:44.508441 IP localhost.localdomain.36770 > mgmt-1.foo.bar.com.domain: 55616+ AAAA? emf.foo.bar.com. (35)
18:47:44.508781 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.36770: 55616 NXDomain* 0/1/0 (95)
18:47:44.509956 IP localhost.localdomain.36770 > mgmt-1.foo.bar.com.domain: 36960+ AAAA? emf. (21)
18:47:44.510371 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.36770: 36960 ServFail 0/0/0 (21)
18:47:47.099560 IP localhost.localdomain.34608 > mgmt-1.foo.bar.com.domain: 51025+ AAAA? emf.foo.bar.com. (35)
18:47:47.100019 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.34608: 51025 NXDomain* 0/1/0 (95)
18:47:47.101436 IP localhost.localdomain.34608 > mgmt-1.foo.bar.com.domain: 53938+ AAAA? emf. (21)
18:47:47.103154 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.34608: 53938 ServFail 0/0/0 (21)
18:49:04.512605 IP localhost.localdomain.42869 > mgmt-1.foo.bar.com.domain: 35026+ AAAA? emf.foo.bar.com. (35)
18:49:04.513069 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.42869: 35026 NXDomain* 0/1/0 (95)
18:49:04.513104 IP localhost.localdomain.42869 > mgmt-1.foo.bar.com.domain: 36535+ AAAA? emf. (21)
18:49:04.513417 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.42869: 36535 ServFail 0/0/0 (21)
18:49:07.108728 IP localhost.localdomain.36998 > mgmt-1.foo.bar.com.domain: 63116+ AAAA? emf.foo.bar.com. (35)
18:49:07.109180 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.36998: 63116 NXDomain* 0/1/0 (95)
18:49:07.109208 IP localhost.localdomain.36998 > mgmt-1.foo.bar.com.domain: 13729+ AAAA? emf. (21)
18:49:07.110817 IP mgmt-1.foo.bar.com.domain > localhost.localdomain.36998: 13729 ServFail 0/0/0 (21)
```

**Comment by slonka** [comment]
hi @jgrund - I'm going to make it configurable. I'll send a PR over probably today.
